on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: eteration.azurecr.io
        username: ${{ secrets.acr_eteration_username }}
        password: ${{ secrets.acr_eteration_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t eteration.azurecr.io/webinar:${{ github.sha }}
        docker push eteration.azurecr.io/webinar:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_webinar_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep webinarba43 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace webinarba43`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: webinarba43
        container-registry-url: eteration.azurecr.io
        container-registry-username: ${{ secrets.acr_eteration_username }}
        container-registry-password: ${{ secrets.acr_eteration_password }}
        secret-name: webinardockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: webinarba43
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          eteration.azurecr.io/webinar:${{ github.sha }}
        imagepullsecrets: |
          webinardockerauth